### ISSUE TITLE
400 (Bad Request)

### ISSUE THREAD

**Issue by zhivko** [jonromero/forex_algotrading#11]
I get this error:
`
.\git\forex_algotrading>python .\post3\runner.py
------ System online ------- 2017-07-02 00:39:28.751531
Bad Request 2017-07-01T22:39:13.752105Z
Traceback (most recent call last):
  File ".\post3\runner.py", line 46, in <module>
    main()
  File ".\post3\runner.py", line 27, in main
    prices = response.get("prices", 200)
  File "C:\Python35\lib\site-packages\v20\response.py", line 30, in get
    raise ResponseUnexpectedStatus(self, status)
v20.errors.ResponseUnexpectedStatus: GET https://api-fxpractice.oanda.com:443/v3/accounts/.../pricing?instruments=E
UR_USD&includeUnitsAvailable=False&since=2017-07-01T22%3A39%3A13.752105Z expected status 200, got 400 (Bad Request)
`
Are examples still working on your side?

**Comment by eddieh800** [comment]
I got the same error and the solution was that I was mistakenly using my login as the account_id. Instead, go to Manage Funds in Oanda (top right) and use the Account Number as the Account ID.
