### ISSUE TITLE
Debugging error 4

### ISSUE THREAD

**Issue by murtagh1** [jonromero/forex_algotrading#5]
I am very VERY new to messing with anything more advanced that using matlab to do matrix equations. I got this bot from on here but even using others I get the same message. The token and ID that used are indeed the correct ones with my account. Please help! I hope this is the right place to ask a question..

Trace back message

ubuntu@ubuntu:~/Downloads/forex_algotrading-master/post3$ python runner.py
------ System online ------- 2016-09-16 21:53:13.002630
Buy at 1.11532
Traceback (most recent call last):
File "runner.py", line 29, in 
main()
File "runner.py", line 23, in main
type='market')
File "/home/ubuntu/Downloads/forex_algotrading-master/post3/oandapy.py", line 73, in create_order
return self.request(endpoint, "POST", params=params)
File "/home/ubuntu/Downloads/forex_algotrading-master/post3/oandapy.py", line 262, in request
raise OandaError(content)
oandapy.OandaError: OANDA API returned error code 4 (The access token provided does not allow this request to be made)

**Comment by murtagh1** [comment]
Cleared up what was going wrong, I needed to contact Oanda to switch my account to "legacy" v1 rest access. Are you still planning on working on the ML code and tutorial?

**Comment by jonromero** [comment]
Yeap, I also just updated the code to use the new OANDA v20 engine. Post coming soon!
